# Generated by Django 4.2.7 on 2023-11-21 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_alter_student_good_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='locker_combination',
            field=models.CharField(default='12-12-12', validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{2}-\\d{2}$', 'Combination must be in the format "12-12-12"')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z]+ [A-Za-z]\\. [A-Za-z]+$', 'Name must be in the format "First Middle Initial. Last"')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator('[\\w]+@school.com', 'Invalid school email format. Please use an email ending with "@school.com".')]),
        ),
    ]
